name: Scraper-Anbima

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6,26,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://laminas-api.anbima.com.br/v2/emissoes/buscar?cnpjEmissor=&cnpjEmissor_desc=&cnpjCoordLider=&cnpjCoordLider_desc=&nomeAgenteFiduciario=&nomeAgenteFiduciario_desc=&originador=&originador_desc=&cedente=&cedente_desc=&devedor=&devedor_desc=&numEmissao=&numEmissao_desc=&numSerie=&numSerie_desc=&indTipoCRI=&indTipoOferta=&codCETIP=&codCETIP_desc=&codISIN=&codISIN_desc=&dataInicial=01%2F01%2F2004&dataFinal=&indTipoIndexador=&percIndexador=&pagina=1&qtdRegistrosPagina=10000 | jq . > cri.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
